### ISSUE TITLE
acfun改版后acfun fix fix失效

### ISSUE THREAD

**Issue by Slept-Warrior** [LKI/acfunfixfix#2]
如[http://www.acfun.tv/v/ac2651981_1](http://www.acfun.tv/v/ac2651981_1)，点击标签中的AFF会提示没有找到可以转换的播放器

**Comment by liriansu-opus** [comment]
了解，这个应该是div id改变了，我去看看

**Comment by liriansu-opus** [comment]
报，好消息是，AcFun Fix Fix已经改好了，现在可以正常转换了。
坏消息是，卖血哥的这个视频因为是投的乐视的，所以正常转换了也无法观看了 QAQ
